### ISSUE TITLE
MQTT - Close/Reconnect cycling

### ISSUE THREAD

**Issue by ludekvodicka** [alladdin/node-lox-mqtt-gateway#1]
Hi, I'm not able to get work your gateway. I'm getting repetitive close-reconnect messages

https://dl.dropboxusercontent.com/u/11355235/ShareX/2017/01/2017-01-08_10-55-59.png

this is my config (I'm not using any login/pass)

```
 "mqtt": {
        "host": "mqtts://homeserver.dum:1883",
        "options": {
            "rejectUnauthorized": false,
            "clientId": "lox_to_mqtt_gateway"
        }
    },
```

Any idea what can be wrong?

**Comment by ludekvodicka** [comment]
This is errors I see in Mosquitto log:

1483858587: New connection from 172.17.0.4 on port 1883.
1483858587: Socket error on client <unknown>, disconnecting.

**Comment by ludekvodicka** [comment]
One more note. Mosquitto_pub/sub works ok on my configuration : https://dl.dropboxusercontent.com/u/11355235/ShareX/2017/01/2017-01-08_11-36-40.png

**Comment by alladdin** [comment]
I think that problem is in mqtts:// because it's for mqtt over ssl. Please use mqtt:// as protocol (without ssl)

**Comment by ludekvodicka** [comment]
Perfect! I didn't noticed it ;-(. It's connected now but with different issue (I will create separated ticket)
