### ISSUE TITLE
Unknown Presence type of control

### ISSUE THREAD

**Issue by aleqcz** [alladdin/node-lox-mqtt-gateway#4]
Hi Luděk,
could you please check 

`2017-06-19T06:37:29.322Z - debug: WebSocketAPI - get structure file 2017-06-19 08:29:18`
`/home/node/node_modules/node-lox-structure-file/lib/Factory.js:74`
`        throw new Error("Invalid type of control '"+value.type+"'");`
`        ^`
` `
`Error: Invalid type of control 'Presence'`
`    at Factory._create_control (/home/node/node_modules/node-lox-structure-file/lib/Factory.js:74:15)`
`    at Factory.<anonymous> (/home/node/node_modules/node-lox-structure-file/lib/Factory.js:54:25)`
`    at Factory.<anonymous> (/home/node/node_modules/node-lox-structure-file/lib/Factory.js:83:35)`
`    at Array.forEach (native)`
`    at Factory._map_list (/home/node/node_modules/node-lox-structure-file/lib/Factory.js:82:23)`
`    at Factory.create_from_json (/home/node/node_modules/node-lox-structure-file/lib/Factory.js:53:41)`
`    at Object.create_from_json (/home/node/node_modules/node-lox-structure-file/lib/Factory.js:92:24)`
`    at API.<anonymous> (/home/node/node_modules/node-lox-mqtt-gateway/bin/lox-mqtt-gateway.js:36:80)`
`    at emitOne (events.js:101:20)`
`    at API.emit (events.js:188:7)`

Perhaps to ignore unknown controls until they are supported and implemented?

Relevant part from the LoxAPP3.json:
`		"0fa1f432-0111-40a5-fffffae984b19f22": {`
`			"name": "Přítomnost v domě",`
`			"type": "Presence",`
`			"uuidAction": "0fa1f432-0111-40a5-fffffae984b19f22",`
`			"room": "0ee48039-033f-81fc-fffffae984b19f22",`
`			"cat": "0d745096-0023-0341-fffffae984b19f22",`
`			"defaultRating": 9,`
`			"isFavorite": false,`
`			"isSecured": false,`
`			"states": {`
`				`
`			}`
`		},`

Thanks a lot, Best regards,
  A.

**Comment by aleqcz** [comment]
![loxone_presence](https://user-images.githubusercontent.com/1750538/27273941-8a79e264-54d1-11e7-93be-e3621604fbbb.PNG)

**Comment by alladdin** [comment]
Presence type of control is not described in Loxone structure file documentation.

There is a fix in version 0.3.1 that logs warning on missing control instead of exit on exception. So that it could be functional with missing control.

**Comment by aleqcz** [comment]
Hello alladdin,
thanks a lot for quick response. I have updated to 0.3.1 and can confirm the issue is gone, unfortunately another one popped out. I'll report it separately.
Thank you
