### ISSUE TITLE
node-lox-mqtt-gateway-0.3.2: CRLF line terminators

### ISSUE THREAD

**Issue by tgurr** [alladdin/node-lox-mqtt-gateway#6]
After installing node-lox-mqtt-gateway:

`# npm install -g node-lox-mqtt-gateway`

when trying to run lox-mqtt-gateway it results in an error:

```
# lox-mqtt-gateway 
/usr/bin/env: ‘node\r’: No such file or directory
```

because of CRLF line terminators:

```
# file lox-mqtt-gateway.js 
lox-mqtt-gateway.js: a /usr/bin/env node script, ASCII text executable, with CRLF line terminators
```
According to npm the line terminators in bin scripts should always have Unix line endings:
https://github.com/npm/npm/issues/12371

Changing them with:
`# sed -i 's/\r//g' lox-mqtt-gateway.js`

```
# file lox-mqtt-gateway.js 
lox-mqtt-gateway.js: a /usr/bin/env node script, ASCII text executable
```

makes lox-mqtt-gateway start:
```
# lox-mqtt-gateway 
2017-08-15T11:40:01.809Z - info: Loxone to MQTT gateway started
```

**Comment by alladdin** [comment]
Fixed in version 3.3
