### ISSUE TITLE
Setup Question: Config file

### ISSUE THREAD

**Issue by christianTF** [alladdin/node-lox-mqtt-gateway#9]
Hello and sorry for this dumb questions, as I am new in node.js.

I've installed node.js (8.15.0) on a Raspberry via the https://deb.nodesource.com repository.
After that, I've installed this package via the mentioned npm command.

Searching for the package, I get the result `/usr/lib/node_modules/node-lox-mqtt-gateway`.

My issue is, that starting the node, I get an error `TypeError: winston.Logger is not a constructor`.

I tried to configure to not use that logger, but now I'm stuck not to find the config file of the package (so, where to write the settings from the "Configuration" section of the readme.

I'm aware, for node.js developers this is a dumb question, but I really haven't found any clear documentation about node.js configs/configfiles.

Thanks for clarification ;-)
Christian

**Comment by fundy77** [comment]
Hi It's not a configuration issue. This module is quite outdated and winston logger module has undergone certain changes in the meantime.  The Logger.js in the source of this node-lox-mqtt-gateway needs to be fixed.  The file is in ...node-lox/mqtt-gateway/lib.  Simply replace on two places of Logger.js the 'new winston.createLogger' with 'winston.createLogger'. That will do the trick.

**Comment by christianTF** [comment]
Thanks @fundy77 !
I will give it a try!
lg, Christian

**Comment by fundy77** [comment]
This is the updated Logger.js:

const winston = require('winston');

var Logger = function(config) {
    if (!config){
        return winston.createLogger({
            transports: [
                new (winston.transports.Console)({
                    timestamp: true,
                    colorize: true,
                    level: 'debug',
                })
            ]
        });
    }

    var transports = [];

    config.forEach(function(item){
        var transport_class = Object.keys(item)[0];
        transports.push(new (winston.transports[transport_class])(
            item[transport_class]
        ));
    });
    var logger = winston.createLogger({transports: transports});
    logger.exitOnError = false;

    return logger;
};

 

module.exports = Logger;

**Comment by fundy77** [comment]
This is the updated Logger.js

`const winston = require('winston');

var Logger = function(config) {
    if (!config){
        return winston.createLogger({
            transports: [
                new (winston.transports.Console)({
                    timestamp: true,
                    colorize: true,
                    level: 'debug',
                })
            ]
        });
    }

    var transports = [];

    config.forEach(function(item){
        var transport_class = Object.keys(item)[0];
        transports.push(new (winston.transports[transport_class])(
            item[transport_class]
        ));
    });
    var logger = winston.createLogger({transports: transports});
    logger.exitOnError = false;

    return logger;
};

 

module.exports = Logger;`

**Comment by christianTF** [comment]
Late feedback, but it worked!
